In [1]:
import pandas as pd
df=pd.read_csv('/content/10 coding question.csv')

In [2]:
df.head(10)

   emp_id   Name Gender   Age Department   Salary   Join_Date
0     101   Aman      M  25.0         IT  55000.0  15-01-2023
1     102  Priya      F  29.0         HR  48000.0  10-11-2022
2     103    Raj      M   NaN    Finance  63000.0  09-05-2024
3     104  Sneha      F  31.0         IT  75000.0  21-08-2021
4     105  Arjun      M  26.0      Sales  46000.0  12-02-2023
5     106   Neha      F  28.0         HR      NaN  01-03-2024
6     107   Ravi      M  24.0      Sales  52000.0  19-07-2023
7     108  Meera      F   NaN    Finance  68000.0  30-09-2022

**Load CSV and check shape, data types, summary**

In [13]:
check_shape=df.shape
print(check_shape)
check_type=df.dtypes
print(check_type)

check_summary=df.info()
print(check_summary)

(8, 7)
emp_id          int64
Name           object
Gender         object
Age           float64
Department     object
Salary        float64
Join_Date      object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      8 non-null      int64
 1   Name        8 non-null      object
 2   Gender      8 non-null      object
 3   Age         6 non-null      float64
 4   Department  8 non-null      object
 5   Salary      7 non-null      float64
 6   Join_Date   8 non-null      object
dtypes: float64(2), int64(1), object(4)
memory usage: 580.0+ bytes
None

**Filter employees having Salary > 50000 and Department = "IT"**

In [14]:
df[(df['Salary']>50000) & (df['Department']=='IT')]

   emp_id   Name Gender   Age Department   Salary   Join_Date
0     101   Aman      M  25.0         IT  55000.0  15-01-2023
3     104  Sneha      F  31.0         IT  75000.0  21-08-2021

Create a new column “Annual_Salary” = Salary * **12**

In [17]:
df['Annual_Salary']=df['Salary']*12
df

   emp_id   Name Gender   Age Department   Salary   Join_Date  Annual_Salary
0     101   Aman      M  25.0         IT  55000.0  15-01-2023       660000.0
1     102  Priya      F  29.0         HR  48000.0  10-11-2022       576000.0
2     103    Raj      M   NaN    Finance  63000.0  09-05-2024       756000.0
3     104  Sneha      F  31.0         IT  75000.0  21-08-2021       900000.0
4     105  Arjun      M  26.0      Sales  46000.0  12-02-2023       552000.0
5     106   Neha      F  28.0         HR      NaN  01-03-2024            NaN
6     107   Ravi      M  24.0      Sales  52000.0  19-07-2023       624000.0
7     108  Meera      F   NaN    Finance  68000.0  30-09-2022       816000.0

Replace all missing values in “Age” column with median

In [31]:
df['Age'].fillna(df['Age'].median())

0    25.0
1    29.0
2    27.0
3    31.0
4    26.0
5    28.0
6    24.0
7    27.0
Name: Age, dtype: float64

**Group employees and find average salary by Department**

In [25]:
df.groupby('Department')['Salary'].mean()

Department
Finance    65500.0
HR         48000.0
IT         65000.0
Sales      49000.0
Name: Salary, dtype: float64

**Find top 3 highest paid employees**

In [27]:
df.sort_values(by='Salary',ascending=False).head(3)

   emp_id   Name Gender   Age Department   Salary   Join_Date  Annual_Salary
3     104  Sneha      F  31.0         IT  75000.0  21-08-2021       900000.0
7     108  Meera      F   NaN    Finance  68000.0  30-09-2022       816000.0
2     103    Raj      M   NaN    Finance  63000.0  09-05-2024       756000.0

**how to find total missing value in your dataframe**

In [32]:
df.isnull().sum()

emp_id           0
Name             0
Gender           0
Age              0
Department       0
Salary           1
Join_Date        0
Annual_Salary    1
dtype: int64

**Create a pivot table: mean Salary by Department vs Gender**

In [35]:
df.pivot_table(
    index='Department',
    columns='Gender',
    values='Salary',
    aggfunc='mean'

)

Gender            F        M
Department
Finance     68000.0  63000.0
HR          48000.0      NaN
IT          75000.0  55000.0
Sales           NaN  49000.0

**Delete duplicate rows**

In [39]:
df.drop_duplicates(inplace=True)
df

   emp_id   Name Gender   Age Department   Salary   Join_Date  Annual_Salary
0     101   Aman      M  25.0         IT  55000.0  15-01-2023       660000.0
1     102  Priya      F  29.0         HR  48000.0  10-11-2022       576000.0
2     103    Raj      M  27.0    Finance  63000.0  09-05-2024       756000.0
3     104  Sneha      F  31.0         IT  75000.0  21-08-2021       900000.0
4     105  Arjun      M  26.0      Sales  46000.0  12-02-2023       552000.0
5     106   Neha      F  28.0         HR      NaN  01-03-2024            NaN
6     107   Ravi      M  24.0      Sales  52000.0  19-07-2023       624000.0
7     108  Meera      F  27.0    Finance  68000.0  30-09-2022       816000.0

**Convert “Join_Date” column to datetime and extract year**

In [42]:
df['Join_Date']=pd.to_datetime(df['Join_Date'])
df['year']=df['Join_Date'].dt.year
df

,emp_id,Name,Gender,Age,Department,Salary,Join_Date,Annual_Salary,year
0,101,Aman,M,25.0,IT,55000.0,2023-01-15,660000.0,2023
1,102,Priya,F,29.0,HR,48000.0,2022-11-10,576000.0,2022
2,103,Raj,M,27.0,Finance,63000.0,2024-05-09,756000.0,2024
3,104,Sneha,F,31.0,IT,75000.0,2021-08-21,900000.0,2021
4,105,Arjun,M,26.0,Sales,46000.0,2023-02-12,552000.0,2023
5,106,Neha,F,28.0,HR,NaN,2024-03-01,NaN,2024
6,107,Ravi,M,24.0,Sales,52000.0,2023-07-19,624000.0,2023
7,108,Meera,F,27.0,Finance,68000.0,2022-09-30,816000.0,2022